language: ruby

rvm:
  - 2.1.0 

env:
  - PUPPET_VERSION="~> 4.0.0"

before_install:
  - gem update bundler
  - bundle --version
  - gem update --system 2.1.11
  - gem --version

script: "rake"

gemfile: Gemfile

sudo: false
