name 'grafjo-sshguard'
version '0.0.1'
author 'Johannes Graf'
license 'MIT License'
project_page 'https://github.com/grafjo/puppet-sshguard'
source 'https://github.com/grafjo/puppet-sshguard.git'
summary 'Puppet module to install sshguard'
description 'A Puppet module to install sshguard'
dependency 'puppetlabs/stdlib'
